export class Account { };
export class NewAdminAccount { };
export class ClientAccount { };
export class Item { };
export class Cart { };
export class Favourites { };
export class Order { };
export class OrdersList { };
export class Db { };